### ISSUE TITLE
把周报做成静态博客

### ISSUE THREAD

**Issue by k997** [hellogcc/osdt-weekly#61]
既然周报都是通过 markdown 发布的，通过 hugo 之类的工具是很容易把 markdown 转为静态博客页面的吧

**Comment by lazyparser** [comment]
嗯，确实，感谢提醒😁

（一直有这个想法，拼接到 hellogcc.org 上去。不过以前 hellogcc.org 是用的 wordpress，最近才转成 markdown，所以是两个 repos。）
