### ISSUE TITLE
关于 OSDT Weekly 每周书评是否取消或拆分剥离的讨论（读者反馈：来自公众号评论）

### ISSUE THREAD

**Issue by lazyparser** [hellogcc/osdt-weekly#7]
在 OSDT Weekly 20200812 的用户评论区，一位读者评论：

> 请问最后的推书环节，能和周报分开吗？这些内容和周报和编译器技术有任何关系吗，而且还是容易引起争论的内容啊。不如开设私人公众号推荐。

小编1号（我）的回复：

> OSDT社区等宗旨为工具链社区开发人员交流和八卦，内容并不局限于技术，关心的八卦也会涉及。每周书评是从第一期开始进行的尝试。争议和争论要是有就好啦你是第一个评论存在意义的。确实可以分开，后续weekly我看看要不要拆分

目前默认的决定是
1. 保留环节，同时
2. 重新强调下是个人表达的一个窗口
3. 重新强调（广告下）书评环节是欢迎和希望社区成员投稿PR的（例如 https://github.com/hellogcc/osdt-weekly/pull/4 ）
4. **新开一个 issue 提供讨论和评论意见，欢迎对 OSDT Weekly 的栏目设定评论和讨论；或提交自己的感兴趣的图书也是欢迎的。**

**Comment by shining1984** [comment]
支持保留该栏目。

可以讨论下书评是否拆分成单独的一篇文章。

对于我个人来说，拆分不拆分，书评我都是要看的，所以对我而言只要保留书评就好了。单独发还是一起发，对于我而言无所谓。

**Comment by lazyparser** [comment]
> 支持保留该栏目。
> 
> 可以讨论下书评是否拆分成单独的一篇文章。
> 
> 对于我个人来说，拆分不拆分，书评我都是要看的，所以对我而言只要保留书评就好了。单独发还是一起发，对于我而言无所谓。

拆分成一篇文章和两篇文章推送都是可以的形式。

分开成单独的书评，就变得更加正式了，那其实要写的更长才行（害怕）

放一起还能偷懒嘻嘻，有时候时间来不及，水两三句话说下自己阅读的感受也是可以的（

**Comment by lazyparser** [comment]
讨论结束；维持原状。
